name: CI
on: [push, pull_request]

jobs:
  test:
    name: Test
    strategy:
      matrix:
        go: ['1.14', '1.15', '1.16', '1.21', '1.22', '1.23']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go }}
    - name: Test
      run: go vet . && go build . && go test -count=1 -covermode=count -coverprofile=coverage.out .
      env:
        GODEBUG: x509sha1=1 # enable SHA1; it's used in the older fixtures
